### ISSUE TITLE
Maybe NexEureka deploy JSON has a typo?

### ISSUE THREAD

**Issue by minyk** [TheNexCloud/NexGate#9]
Hello,

NexEureka.json has below lines: 
```
    "labels": {
        "MARATHON_TASKS_ENDPOINT": "http://leader.mesos:8080/v2/tasks",
        "EUREKA_ENDPOINT": "http://nexrouter.marathon.mesos:8770/eureka/apps/"
```

IMO, it is `env`, not `labels`. Am I wrong?

Thanks.

**Comment by ssipflow** [comment]
Yes, it is `env`. We mistook it. Thanks.

**Comment by ssipflow** [comment]
We just updated JSON configuration and manual.

[nexeureka.json](https://github.com/TheNexCloud/NexGate/blob/master/nexeureka.json)
[nexzuul.json](https://github.com/TheNexCloud/NexGate/blob/master/nexzuul.json)
[README.md](https://github.com/TheNexCloud/NexGate/blob/master/README.md)

Thank you for your opinion.

**Comment by minyk** [comment]
LGTM, Thanks!
